### PR TITLE
Crypto Raamwerk.doc naar Crypto Raamwerk.md

### PR DESCRIPTION
**Pull request by lennert212**
Hierbij mijn versie van Crypto Raamwerk.md.

Lennert

### CODE REVIEW

**Comment by ijansch** [comment]
Top werk! Zou je totdat we kunnen beslissen of we in markdown verder mogen gaan even de disclaimer uit de readme van de repo willen toevoegen? Dan kunnen we de md file nu alvast plaatsen.

**Comment by lennert212** [comment]
Having issues with being new to Github and having unverified commits. Have another appointment but should be able to fix it later today!

**Comment by dirkx** [comment]
I usually do:

   git filter-branch --commit-filter 'git commit-tree -S "$@";' XXX..HEAD

where XXX is the first commit you started at. This has the nice benefit that it does not alter the commit metadata (including commit date, history, log, etc).

And then push.

**Comment by lennert212** [comment]
Looks like that worked:

Lennerts-iMac-2015:nl-covid19-notification-app-coordination lennert$ git filter-branch --commit-filter 'git commit-tree -S "$@";' a14761c879fedc530342b66fca9d4dcb41c9c629..HEAD
Rewrite 212f872821294b4e3d32f797a5434fa9e33737a6 (17/21) (3 seconds passed, remaining 0 predicted)    
Ref 'refs/heads/master' was rewritten

**Comment by lennert212** [comment]
Closing the pull request. Getting all kinds of conflicts while trying to squash commits.

**Pull request closed without merging**
